### ISSUE TITLE
Notify user on invalid inputs or request error

### ISSUE THREAD

**Issue by LordOfTheNeverThere** [HackerSchool/Arquimedia#120]
Currently in Registration some form errors are not prompted to the user

-  Such as having a same email as an already registered account
- Or an incorrect username character

![image](https://user-images.githubusercontent.com/80652363/159380635-25058447-bbe5-4e01-a287-ac8f8f7bbac1.png)

This info should be given to the user!

**Comment by JeronimoMendes** [comment]
This issue can also be extended to the login page. Users should get notified when the password is incorrect and username doesn't exist.

**Comment by JeronimoMendes** [comment]
Notifications should be done using `notistack`.
