### ISSUE TITLE
Add Reset Password Connection on the Login Page

### ISSUE THREAD

**Issue by LordOfTheNeverThere** [HackerSchool/Arquimedia#177]
The current login page lacks the functionality to redirect to the reset password page, this should be looked upon.

**Comment by JeronimoMendes** [comment]
And maybe add a link to the registration page as well

**Comment by LordOfTheNeverThere** [comment]
Thinking about it it's pretty unusual to put the link in the registration form, since the user is defining its password there.

**Comment by JeronimoMendes** [comment]
I meant add a link, in the login page, that redirects the user to the registration page, as he may have ended up there by mistake. @LordOfTheNeverThere
